In [2]:
import pynoma
import pyabraom
import pandas as pd
import numpy as np

In [3]:
g38 = pd.read_csv("./data/gnomad3.csv")
a38 = pd.read_csv("./data/abrhg38.csv")

In [4]:
a38

,Chromosome,Position,Reference,Alternative,Annotation,Gene,rsID,GATK Filter,Number of Homozygotes,Allele Number,Allele Count,Allele Frequency,Number of Hemizygotes
0,4,987095,T,C,nonsynonymous SNV,IDUA,rs180984980,PASS,0,2342,7,0.002989,NaN
1,4,987108,C,A,synonymous SNV,IDUA,rs11248061,PASS,223,2342,977,0.417165,NaN
2,4,987114,-,CTGGCGCTC,nonframeshift insertion,IDUA,NaN,PASS,0,2342,3,0.001281,NaN
3,4,987144,G,A,synonymous SNV,IDUA,rs10902762,PASS,224,2342,981,0.418873,NaN
4,4,987161,C,-,frameshift deletion,IDUA,NaN,PASS,0,2338,1,0.000428,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5570,2,26244392,C,T,intronic,HADHA,rs193147804,PASS,0,2342,6,0.002562,NaN
5571,2,26244477,G,C,intronic,HADHA,rs917266513,PASS,0,2342,1,0.000427,NaN
5572,2,26244479,C,A,intronic,HADHA,rs62128457,PASS,46,2342,428,0.182750,NaN
5573,2,26244597,C,A,UTR5,HADHA,rs72809666,PASS,0,2342,5,0.002135,NaN
5574,2,26244621,G,C,UTR5,HADHA,rs184300489,PASS,0,2342,7,0.002989,NaN

In [6]:
a38.dtypes

Chromosome                object
Position                   int64
Reference                 object
Alternative               object
Annotation                object
Gene                      object
rsID                      object
GATK Filter               object
Number of Homozygotes      int64
Allele Number              int64
Allele Count               int64
Allele Frequency         float64
Number of Hemizygotes    float64
dtype: object

In [5]:
ls = pyabraom.Variant_ID_biovar(a38, "hg38")

TypeError: must be str, not numpy.int64

In [5]:
g38.columns

Index(['Variant ID', 'rsID', 'Gene', 'Consequence', 'Annotation', 'Flags',
       'Allele Count', 'Allele Number', 'Allele Frequency',
       'Number of Homozygotes', 'Source', 'Chromosome', 'Location',
       'Reference', 'Alternative', 'Number of Hemizygotes'],
      dtype='object')

In [6]:
a38.columns

Index(['Chr', 'Start', 'Ref', 'Alt', 'Gene', 'GATK Filter', 'Annotation',
       'Homozygotes', 'Allele Number', 'Allele Alt', 'Frequencie'],
      dtype='object')

In [ ]:
a38 = a38.rename(columns={'Alt': 'Alternative', 'Ref':'Reference'})